import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SiteHeader from "@/features/header/SiteHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Nextjs playground",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header>
					<SiteHeader />
				</header>
				{children}
			</body>
		</html>
	);
}
